// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

// This test suite runs each operation test in parallel.
// Example, if your database has 3 tables, the suite will run:
// table1, table2 and table3 Delete in parallel
// table1, table2 and table3 Insert in parallel, and so forth.
// It does NOT run each operation group in parallel.
// Separating the tests thusly grants avoidance of Postgres deadlocks.
func TestParent(t *testing.T) {
	t.Run("Works", testWorks)
}

func TestDelete(t *testing.T) {
	t.Run("Works", testWorksDelete)
}

func TestQueryDeleteAll(t *testing.T) {
	t.Run("Works", testWorksQueryDeleteAll)
}

func TestSliceDeleteAll(t *testing.T) {
	t.Run("Works", testWorksSliceDeleteAll)
}

func TestExists(t *testing.T) {
	t.Run("Works", testWorksExists)
}

func TestFind(t *testing.T) {
	t.Run("Works", testWorksFind)
}

func TestBind(t *testing.T) {
	t.Run("Works", testWorksBind)
}

func TestOne(t *testing.T) {
	t.Run("Works", testWorksOne)
}

func TestAll(t *testing.T) {
	t.Run("Works", testWorksAll)
}

func TestCount(t *testing.T) {
	t.Run("Works", testWorksCount)
}

func TestHooks(t *testing.T) {
	t.Run("Works", testWorksHooks)
}

func TestInsert(t *testing.T) {
	t.Run("Works", testWorksInsert)
	t.Run("Works", testWorksInsertWhitelist)
}

// TestToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestToOne(t *testing.T) {}

// TestOneToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOne(t *testing.T) {}

// TestToMany tests cannot be run in parallel
// or deadlocks can occur.
func TestToMany(t *testing.T) {}

// TestToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneSet(t *testing.T) {}

// TestToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneRemove(t *testing.T) {}

// TestOneToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneSet(t *testing.T) {}

// TestOneToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneRemove(t *testing.T) {}

// TestToManyAdd tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyAdd(t *testing.T) {}

// TestToManySet tests cannot be run in parallel
// or deadlocks can occur.
func TestToManySet(t *testing.T) {}

// TestToManyRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyRemove(t *testing.T) {}

func TestReload(t *testing.T) {
	t.Run("Works", testWorksReload)
}

func TestReloadAll(t *testing.T) {
	t.Run("Works", testWorksReloadAll)
}

func TestSelect(t *testing.T) {
	t.Run("Works", testWorksSelect)
}

func TestUpdate(t *testing.T) {
	t.Run("Works", testWorksUpdate)
}

func TestSliceUpdateAll(t *testing.T) {
	t.Run("Works", testWorksSliceUpdateAll)
}
