[psql]
    dbname = "sre53"
    host   = "localhost"
    port   = 5432
    user   = "sre53"
    pass   = "wordpass"
    schema = "api"
    blacklist = ["migrations", "other"]
    sslmode = "disable"

[sqlite3]
    dbname = "data.sqlite3"